name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ["bug-report"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of NavKeys are you using?
      options:
        - 1.0 (Latest)
        - 0.5
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Opera
        - Edge
        - Other
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Browser
      description: What type of device are you using?
      options:
        - Dekstop
        - Mobile/Tablet
    validations:
      required: true


