name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ["bug-report"]
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of NavKeys are you using?
      options:
        - 0.5
        - 1.0 (Latest)
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Opera
        - Edge
    validations:
      required: true


